import Head from 'next/head';
import { ReactElement } from 'react';
import { Layout } from 'src/components/Layout';
import { NextPageWithLayout } from 'src/types/types';

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Hello World</main>
    </div>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
