import Head from 'next/head';
import React, { ReactElement, useState } from 'react';
import { Layout } from 'src/components/Layout';
import { NextPageWithLayout } from 'src/types/types';
import Calendar from 'react-calendar';
import Link from 'next/link';

const Home: NextPageWithLayout = () => {
  const [date, setDate] = useState(new Date());
  const displayDate = `${date.getFullYear()}年${date.getMonth()}月`;

  // mock
  const data = [
    {
      name: 'Ma-sa',
      score: 80,
      bestCategory: '風呂掃除',
    },
    {
      name: 'San',
      score: 50,
      bestCategory: 'ゴミ捨て',
    },
  ];

  type RegisterButtonProps = JSX.IntrinsicElements['a'];
  // eslint-disable-next-line react/display-name
  const RegisterButton = React.forwardRef<
    HTMLAnchorElement,
    RegisterButtonProps
  >((props, ref) => {
    const { href, onClick } = props;
    return (
      <a
        className="block rounded theme-blue2 shadow-lg p-3 w-1/4 hover:opacity-80 font-semibold mr-5 text-center cursor-pointer"
        href={href}
        onClick={onClick}
        ref={ref}
      >
        家事を登録する
      </a>
    );
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-12">
        <div className="col-span-4 p-3">
          <div className="rounded shadow-lg p-3 theme-green2">
            <Calendar locale="ja-JP" onChange={setDate} value={date} />
          </div>
        </div>
        <div className="col-span-8 p-3">
          <div
            className="theme-blue3 rounded shadow-lg p-3 flex flex-col justify-center"
            style={{ height: '1000px' }}
          >
            <div className="border-b pb-5 border-gray-700">
              <div className="text-center font-semibold text-3xl">
                {displayDate}
              </div>
              <button className="block rounded theme-blue2 shadow-lg ml-auto p-3 w-1/4 hover:opacity-80 font-semibold">
                月末締め
              </button>
            </div>
            <div className="mt-5 mb-5">
              <div className="text-right font-semibold text-2xl">
                一番頑張っている家事
              </div>
              {data &&
                data.map((d, i) => {
                  return (
                    <React.Fragment key={`Home-${i}`}>
                      <div className="grid grid-cols-3 mt-5">
                        <div className="col-span-1 text-center font-semibold text-2xl">
                          {d.name}
                        </div>
                        <div className="col-span-1 text-center font-semibold text-2xl">
                          {`${d.score}点`}
                        </div>
                        <div className="col-span-1 text-center font-semibold text-2xl">
                          {d.bestCategory}
                        </div>
                      </div>
                    </React.Fragment>
                  );
                })}
            </div>
            <div className="flex justify-center pt-5 border-t border-gray-700">
              <button className="block rounded theme-blue2 shadow-lg p-3 w-1/4 hover:opacity-80 font-semibold mr-5">
                家事を入力する
              </button>
              <Link href={'/register'}>
                <RegisterButton />
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <Layout>{page}</Layout>;

export default Home;
